[project]
name = "agent"
version = "0.1.0"
description = "智能体学习项目"
authors = [
    {name = "ling"}
]
readme = "README.md"
requires-python = "3.12.3"
dependencies = [
    "langchain (>=1.2.14,<2.0.0)",
    "langchain-ollama (>=1.0.1,<2.0.0)",
    "langgraph (>=1.1.4,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
